version: '3.8'
services:
  backend:
    image: vishalsainani/my-chat-app_backend:latest
    build: ./backend
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/index
      - ./app/node_modules
  frontend:
    image: vishalsainani/my-chat-app_frontend:latest
    build: ./frontend
    container_name: client_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - ./srv/app/node_modules
    stdin_open: true
    tty: true
