version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - /home/ubuntu/chatapp-react-node-js/backend/.env.local
    container_name: api_backend
    ports:
      - '4000:4000'
    # volumes:
    #   - ./backend:/index
    #   - ./app/node_modules
  frontend:
    build: ./frontend
    container_name: client_frontend
    ports:
      - '5173:5173'
    #   volumes:
    #     - ./frontend:/app
    #     - ./srv/app/node_modules
    #   stdin_open: true
    #   tty: true
